"""
Django settings for bramas_jaya project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(path):
    """Loader .env sederhana — tidak butuh package tambahan (python-dotenv dll)."""
    if not path.exists():
        return
    for line in path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key.strip(), value)


_load_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Diambil dari environment variable / file .env, BUKAN hardcoded di kode.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-CHANGE-THIS-KEY-BEFORE-PRODUCTION',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Default-nya False (aman) kalau env var tidak diset sama sekali.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').strip().lower() == 'true'

allowed_hosts = [
    h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()
]

for env_name in ('WEBSITE_HOSTNAME', 'RENDER_EXTERNAL_HOSTNAME', 'VIRTUAL_HOST'):
    value = os.environ.get(env_name, '').strip()
    if value:
        allowed_hosts.append(value)

app_url = os.environ.get('APP_URL', '').strip()
if app_url:
    allowed_hosts.append(urlparse(app_url).netloc)

if not allowed_hosts:
    allowed_hosts = ['localhost', '127.0.0.1', '0.0.0.0', '[::1]', '*']

ALLOWED_HOSTS = allowed_hosts

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

csrf_origins = [
    origin.strip() for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()
]
if app_url:
    parsed = urlparse(app_url)
    if parsed.scheme and parsed.netloc:
        origin = f"{parsed.scheme}://{parsed.netloc}"
        if origin not in csrf_origins:
            csrf_origins.append(origin)

# Otomatis tambahkan trusted origin dari ALLOWED_HOSTS bila belum dikonfigurasi.
if not csrf_origins:
    for host in allowed_hosts:
        if not host or host in ['localhost', '127.0.0.1', '0.0.0.0', '[::1]', '*']:
            continue
        if host.startswith('[') or host[0].isdigit():
            schemes = ['http://', 'https://']
        else:
            schemes = ['https://', 'http://']
        for scheme in schemes:
            origin = f"{scheme}{host}"
            if origin not in csrf_origins:
                csrf_origins.append(origin)

CSRF_TRUSTED_ORIGINS = csrf_origins

if app_url and app_url.startswith('https://'):
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
else:
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'toko'
]

AUTHENTICATION_BACKENDS = [
    'toko.auth_backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bramas_jaya.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bramas_jaya.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
SESSION_COOKIE_NAME = 'bramasjaya_session'
MEDIA_URL = os.environ.get('MEDIA_URL', '/media/')
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Ongkir flat berdasarkan area (Jawa vs Luar Jawa) — lihat toko/views.py
ONGKIR_JAWA = 25000
ONGKIR_LUAR_JAWA = 50000