# Generated by Django 6.0.5 on 2026-05-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kategori', models.CharField(choices=[('Tepung Terigu', 'Tepung Terigu'), ('Tepung Beras', 'Tepung Beras'), ('Tepung Tapioka', 'Tepung Tapioka'), ('Tepung Spesial', 'Tepung Spesial')], max_length=50)),
                ('deskripsi', models.TextField()),
                ('harga', models.IntegerField()),
                ('berat', models.CharField(max_length=50)),
                ('stok', models.IntegerField(default=0)),
                ('emoji', models.CharField(default='🌾', max_length=10)),
                ('tersedia', models.BooleanField(default=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Daftar Produk',
            },
        ),
    ]
