# Generated by Django 6.0.5 on 2026-05-24 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DompetAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.BigIntegerField(default=0)),
                ('diperbarui', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dompet Admin',
                'verbose_name_plural': 'Dompet Admin',
            },
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_pesanan', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Pembayaran'), ('dibayar', 'Sudah Dibayar'), ('diproses', 'Sedang Diproses'), ('dikirim', 'Sedang Dikirim'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='menunggu', max_length=20)),
                ('nama_penerima', models.CharField(max_length=200)),
                ('telepon', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
                ('metode_pengiriman', models.CharField(max_length=100)),
                ('metode_pembayaran', models.CharField(max_length=100)),
                ('ongkir', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('bukti_bayar', models.ImageField(blank=True, null=True, upload_to='bukti_bayar/')),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pesanan',
                'verbose_name_plural': 'Daftar Pesanan',
            },
        ),
        migrations.CreateModel(
            name='ItemPesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produk_nama', models.CharField(max_length=200)),
                ('produk_emoji', models.CharField(max_length=10)),
                ('harga', models.IntegerField()),
                ('jumlah', models.IntegerField()),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='toko.pesanan')),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatDompet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('keterangan', models.CharField(max_length=200)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('pesanan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toko.pesanan')),
            ],
            options={
                'verbose_name': 'Riwayat Dompet',
                'verbose_name_plural': 'Riwayat Dompet',
            },
        ),
    ]
