# Generated by Django 6.0.5 on 2026-06-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0002_dompetadmin_pesanan_itempesanan_riwayatdompet'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='produk/'),
        ),
    ]
