# Generated by Django 6.0.5 on 2026-06-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0003_produk_gambar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekeningAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode', models.CharField(choices=[('transfer', 'Transfer Bank'), ('qris', 'QRIS')], max_length=20)),
                ('nama_bank', models.CharField(help_text='Contoh: Bank BCA', max_length=100)),
                ('nomor', models.CharField(help_text='Nomor rekening atau nomor QRIS', max_length=100)),
                ('atas_nama', models.CharField(help_text='Nama pemilik rekening', max_length=100)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rekening Admin',
                'verbose_name_plural': 'Rekening Admin',
            },
        ),
    ]
