# Generated by Django 6.0.5 on 2026-06-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0004_rekeningadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekeningadmin',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Upload foto/gambar QR Code QRIS', null=True, upload_to='qris/'),
        ),
    ]
