# Generated by Django 6.0.5 on 2026-06-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0005_rekeningadmin_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='alasan_batal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
