# Generated by Django 6.0.5 on 2026-06-20 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0006_pesanan_alasan_batal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ulasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produk_nama', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=5)),
                ('komentar', models.TextField()),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ulasan', to='toko.pesanan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ulasan',
                'verbose_name_plural': 'Daftar Ulasan',
            },
        ),
    ]
