# Generated by Django 6.0.5 on 2026-06-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0007_ulasan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('tipe', models.CharField(choices=[('persen', 'Persentase (%)'), ('nominal', 'Nominal (Rp)')], default='persen', max_length=10)),
                ('nilai', models.IntegerField(help_text='Nilai diskon: % atau Rp')),
                ('min_belanja', models.IntegerField(default=0, help_text='Minimum belanja (0 = tidak ada minimum)')),
                ('maks_diskon', models.IntegerField(default=0, help_text='Maksimum diskon Rp (0 = tidak dibatasi)')),
                ('aktif', models.BooleanField(default=True)),
                ('kadaluarsa', models.DateField(blank=True, help_text='Kosongkan jika tidak ada batas waktu', null=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ulasan',
                'verbose_name_plural': 'Daftar Ulasan',
            },
        ),
        migrations.AlterModelOptions(
            name='ulasan',
            options={},
        ),
    ]
