# Generated by Django 6.0.5 on 2026-06-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0008_kupon_alter_ulasan_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kupon',
            options={'verbose_name': 'Kupon', 'verbose_name_plural': 'Daftar Kupon'},
        ),
        migrations.AlterModelOptions(
            name='ulasan',
            options={'verbose_name': 'Ulasan', 'verbose_name_plural': 'Daftar Ulasan'},
        ),
    ]
