# Generated by Django 6.0.5 on 2026-06-24 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0009_alter_kupon_options_alter_ulasan_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KonfigurasiPoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poin_per_pesanan', models.IntegerField(default=1, help_text='Poin yang didapat per pesanan selesai')),
                ('target_tukar', models.IntegerField(default=10, help_text='Jumlah poin yang dibutuhkan untuk ditukar')),
                ('nilai_diskon', models.IntegerField(default=10000, help_text='Nilai diskon (Rp) per penukaran')),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Konfigurasi Poin',
                'verbose_name_plural': 'Konfigurasi Poin',
            },
        ),
        migrations.CreateModel(
            name='PoinPelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_poin', models.IntegerField(default=0)),
                ('diperbarui', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poin Pelanggan',
                'verbose_name_plural': 'Daftar Poin Pelanggan',
            },
        ),
        migrations.CreateModel(
            name='RiwayatPoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('tambah', 'Poin Ditambah'), ('tukar', 'Poin Ditukarkan')], max_length=10)),
                ('jumlah', models.IntegerField()),
                ('keterangan', models.CharField(max_length=200)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riwayat Poin',
                'verbose_name_plural': 'Riwayat Poin',
            },
        ),
    ]
