# Generated by Django 6.0.6 on 2026-06-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0010_konfigurasipoin_poinpelanggan_riwayatpoin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kupon',
        ),
        migrations.AddField(
            model_name='itempesanan',
            name='produk_gambar',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
